### ISSUE TITLE
v0.30.2 crashes

### ISSUE THREAD

**Issue by ekkis** [EmberStake/namada-selfhost#11]
I edited my `.env` to contain `NAMADA_TAG=v0.30.2` and did a docker pull, down and up and the containers fail to come up.  I'm sharing the logs below.  what else do I need to do for an upgrade?

> Downloading config release from http://namada-1:8123/local.af25e423983e63d2105da665.tar.gz ...
> 2024-01-29 13:10:02 Error downloading release: HTTP status client error (404 Not Found) for url (http://namada-1:8123/local.af25e423983e63d2105da665.tar.gz)
> 2024-01-29 13:10:02 cp: target '/root/.local/share/namada/local.af25e423983e63d2105da665/wasm' is not a directory
> 2024-01-29 13:10:02 cp: cannot create regular file '/root/.local/share/namada/local.af25e423983e63d2105da665/wasm': No such file or directory
> 2024-01-29 13:10:02 sed: can't read /root/.local/share/namada/local.af25e423983e63d2105da665/config.toml: No such file or directory
> 2024-01-29 13:10:02 sed: can't read /root/.local/share/namada/local.af25e423983e63d2105da665/config.toml: No such file or directory
> 2024-01-29 13:10:02 sed: can't read /root/.local/share/namada/local.af25e423983e63d2105da665/config.toml: No such file or directory
> 2024-01-29 13:10:02 sed: can't read /root/.local/share/namada/local.af25e423983e63d2105da665/config.toml: No such file or directory
> 2024-01-29 13:10:02 The application panicked (crashed).
> 2024-01-29 13:10:02 Message:  Missing genesis files: 
> 2024-01-29 13:10:02    0: Couldn't read Validity predicates config file from /root/.local/share/namada/local.af25e423983e63d2105da665/validity-predicates.toml
> 2024-01-29 13:10:02    1: No such file or directory (os error 2)
> 2024-01-29 13:10:02 
> 2024-01-29 13:10:02 Location:
> 2024-01-29 13:10:02    crates/apps/src/lib/config/genesis/utils.rs:24
> 2024-01-29 13:10:02 
> 2024-01-29 13:10:02 Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
> 2024-01-29 13:10:02 Run with RUST_BACKTRACE=full to include source snippets.
> 2024-01-29 13:10:02 Location: crates/apps/src/lib/cli/context.rs:114
> 2024-01-29 13:10:02 
> 2024-01-29 13:10:02 Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
> 2024-01-29 13:10:02 Run with RUST_BACKTRACE=full to include source snippets.

**Comment by 0x4r45h** [comment]
did you removed the container volumes too?
docker compose down -v

**Comment by ekkis** [comment]
ah, no.  let me do that

**Comment by ekkis** [comment]
ok.  that solved the problem.  a million thanks.  the `interface-1` is still crashing but I'll report that separately
