### ISSUE TITLE
`interface-1` container crashes

### ISSUE THREAD

**Issue by ekkis** [EmberStake/namada-selfhost#12]
here's what I see (incidentally, this predates the current version.  I experienced this in 0.30.0 as well):

> 2024-01-29 14:52:59 sed: can't read packages/types/src/tx/tokens/types/index.ts: No such file or directory
> 2024-01-29 14:52:59 sed: can't read packages/types/src/tx/tokens/types/index.ts: No such file or directory
> 2024-01-29 14:52:59 /docker-entrypoint-scripts.d/start-node.sh: 35: cannot create //apps/namada-interface/.env: Directory nonexistent
> 2024-01-29 14:52:59 /docker-entrypoint-scripts.d/start-node.sh: 39: yarn: not found
> 2024-01-29 14:52:59 /docker-entrypoint-scripts.d/start-node.sh: 42: cd: can't cd to //apps/namada-interface
> 2024-01-29 14:52:59 /docker-entrypoint-scripts.d/start-node.sh: 43: yarn: not found
> 2024-01-29 14:52:59 /docker-entrypoint-scripts.d/start-node.sh: 46: cd: can't cd to //apps/extension
> 2024-01-29 14:52:59 /docker-entrypoint-scripts.d/start-node.sh: 48: yarn: not found
> 2024-01-29 14:52:59 /docker-entrypoint-scripts.d/start-node.sh: 50: yarn: not found
> 2024-01-29 14:52:59 cp: 'build/.' and '/build/.' are the same file
> 2024-01-29 14:52:59 /docker-entrypoint-scripts.d/start-node.sh: 58: cd: can't cd to //apps/namada-interface
> 2024-01-29 14:52:59 /docker-entrypoint-scripts.d/start-node.sh: 60: yarn: not found
> 2024-01-29 14:53:02 sed: can't read packages/types/src/tx/tokens/types/index.ts: No such file or directory
> 2024-01-29 14:53:02 sed: can't read packages/types/src/tx/tokens/types/index.ts: No such file or directory
> 2024-01-29 14:53:02 /docker-entrypoint-scripts.d/start-node.sh: 35: cannot create //apps/namada-interface/.env: Directory nonexistent
> 2024-01-29 14:53:02 /docker-entrypoint-scripts.d/start-node.sh: 39: yarn: not found
> 2024-01-29 14:53:02 /docker-entrypoint-scripts.d/start-node.sh: 42: cd: can't cd to //apps/namada-interface
> 2024-01-29 14:53:02 /docker-entrypoint-scripts.d/start-node.sh: 43: yarn: not found
> 2024-01-29 14:53:02 /docker-entrypoint-scripts.d/start-node.sh: 46: cd: can't cd to //apps/extension
> 2024-01-29 14:53:02 /docker-entrypoint-scripts.d/start-node.sh: 48: yarn: not found
> 2024-01-29 14:53:02 /docker-entrypoint-scripts.d/start-node.sh: 50: yarn: not found
> 2024-01-29 14:52:59 Chain id is local.9ccae3a9a553a669fabd8378
> 2024-01-29 14:52:59 Building shared dependencies, this gonna takes a long time
> 2024-01-29 14:52:59 Building Interface
> 2024-01-29 14:52:59 Building extensions
> 2024-01-29 14:52:59 starting server...
> 2024-01-29 14:53:02 Chain id is local.9ccae3a9a553a669fabd8378
> 2024-01-29 14:53:02 Building shared dependencies, this gonna takes a long time
> 2024-01-29 14:53:02 Building Interface
> 2024-01-29 14:53:02 Building extensions
> 2024-01-29 14:53:02 starting server...
> 2024-01-29 14:53:02 cp: 'build/.' and '/build/.' are the same file
> 2024-01-29 14:53:02 /docker-entrypoint-scripts.d/start-node.sh: 58: cd: can't cd to //apps/namada-interface
> 2024-01-29 14:53:02 /docker-entrypoint-scripts.d/start-node.sh: 60: yarn: not found
> 2024-01-29 14:53:03 sed: can't read packages/types/src/tx/tokens/types/index.ts: No such file or directory
> 2024-01-29 14:53:03 sed: can't read packages/types/src/tx/tokens/types/index.ts: No such file or directory
> 2024-01-29 14:53:03 /docker-entrypoint-scripts.d/start-node.sh: 35: cannot create //apps/namada-interface/.env: Directory nonexistent
> 2024-01-29 14:53:03 /docker-entrypoint-scripts.d/start-node.sh: 39: yarn: not found
> 2024-01-29 14:53:03 /docker-entrypoint-scripts.d/start-node.sh: 42: cd: can't cd to //apps/namada-interface
> 2024-01-29 14:53:03 /docker-entrypoint-scripts.d/start-node.sh: 43: yarn: not found
> 2024-01-29 14:53:03 /docker-entrypoint-scripts.d/start-node.sh: 46: cd: can't cd to //apps/extension
> 2024-01-29 14:53:03 /docker-entrypoint-scripts.d/start-node.sh: 48: yarn: not found
> 2024-01-29 14:53:03 /docker-entrypoint-scripts.d/start-node.sh: 50: yarn: not found
> 2024-01-29 14:53:03 cp: 'build/.' and '/build/.' are the same file
> 2024-01-29 14:53:03 /docker-entrypoint-scripts.d/start-node.sh: 58: cd: can't cd to //apps/namada-interface
> 2024-01-29 14:53:03 /docker-entrypoint-scripts.d/start-node.sh: 60: yarn: not found
> 2024-01-29 14:53:04 sed: can't read packages/types/src/tx/tokens/types/index.ts: No such file or directory
> 2024-01-29 14:53:04 sed: can't read packages/types/src/tx/tokens/types/index.ts: No such file or directory
> 2024-01-29 14:53:04 /docker-entrypoint-scripts.d/start-node.sh: 35: cannot create //apps/namada-interface/.env: Directory nonexistent
> 2024-01-29 14:53:04 /docker-entrypoint-scripts.d/start-node.sh: 39: yarn: not found
> 2024-01-29 14:53:04 /docker-entrypoint-scripts.d/start-node.sh: 42: cd: can't cd to //apps/namada-interface
> 2024-01-29 14:53:04 /docker-entrypoint-scripts.d/start-node.sh: 43: yarn: not found
> 2024-01-29 14:53:04 /docker-entrypoint-scripts.d/start-node.sh: 46: cd: can't cd to //apps/extension
> 2024-01-29 14:53:03 Chain id is local.9ccae3a9a553a669fabd8378
> 2024-01-29 14:53:03 Building shared dependencies, this gonna takes a long time
> 2024-01-29 14:53:03 Building Interface
> 2024-01-29 14:53:03 Building extensions
> 2024-01-29 14:53:03 starting server...
> 2024-01-29 14:53:04 Chain id is local.9ccae3a9a553a669fabd8378
> 2024-01-29 14:53:04 Building shared dependencies, this gonna takes a long time
> 2024-01-29 14:53:04 Building Interface
> 2024-01-29 14:53:04 Building extensions
> 2024-01-29 14:53:04 /docker-entrypoint-scripts.d/start-node.sh: 48: yarn: not found
> 2024-01-29 14:53:04 /docker-entrypoint-scripts.d/start-node.sh: 50: yarn: not found
> 2024-01-29 14:53:04 cp: 'build/.' and '/build/.' are the same file
> 2024-01-29 14:53:04 /docker-entrypoint-scripts.d/start-node.sh: 58: cd: can't cd to //apps/namada-interface
> 2024-01-29 14:53:04 starting server...
> 2024-01-29 14:53:04 /docker-entrypoint-scripts.d/start-node.sh: 60: yarn: not found
>

**Comment by 0x4r45h** [comment]
i have pushed wrong image as interface.    
try to pull images again, it should work now.    
by the way, note that you don't have to run the interface container if you don't want to work with interface/extension.

**Comment by ekkis** [comment]
`$ docker compose pull`

> [+] Running 2/4
>  ⠿ namada-2 Skipped - Image is already being pulled by namada-1                                           0.0s
>  ⠿ namada-3 Skipped - Image is already being pulled by namada-1                                           0.0s
>  ⠿ interface Warning                                                                                     11.4s
>  ⠿ namada-1 Warning                                                                                      11.4s
> WARNING: Some service image(s) must be built from source by running:
>     docker compose build namada-1 interface
> 2 errors occurred:
> 	* Error response from daemon: Get "https://registry-1.docker.io/v2/": net/http: TLS handshake timeout
> 	* Error response from daemon: Get "https://registry-1.docker.io/v2/": net/http: TLS handshake timeout

**Comment by ekkis** [comment]
that seemed transient.  I'm pulling again

**Comment by ekkis** [comment]
ok.  all good now.  I get a page.  yay!
