### ISSUE TITLE
Unable to Fetch Shielded balance

### ISSUE THREAD

**Issue by chimmykk** [EmberStake/namada-selfhost#21]
Any docs or config that needs to be review to enable shielded balance feature

**Comment by 0x4r45h** [comment]
i just tested it and it works out of the box. make sure tear down everything, update namada version in .env file and pull images.

```bash
namadaw gen --shielded --alias shield-1 --unsafe-dont-encrypt

namadaw gen-payment-addr --key shield-1 --alias shield-1-addr-1

namadac transfer  --source namada-1-wallet --target shield-1-addr-1 --token nam  --amount 10

namadac balance --owner shield-1

Last committed epoch: 240
nam : 10
```

**Comment by chimmykk** [comment]
i mean on the interface, namada interface, transparent balance shows up except for the shielded balance, https://github.com/anoma/namada-interface

**Comment by 0x4r45h** [comment]
oh, the interface version is a bit outdated. it evolves too quickly to maintain. I'm waiting for a stable version to upgrade it

**Comment by chimmykk** [comment]
any docs or update i need to make changes for the shielded balance display,

**Comment by 0x4r45h** [comment]
tbh I have no idea about it, you have to dig into the source code of the namada-interface

**Comment by chimmykk** [comment]
one question how do i get token addres and denom of atom?
