### ISSUE TITLE
Version updates

### ISSUE THREAD

**Issue by ekkis** [EmberStake/namada-selfhost#9]
the repo indicates a `NAMADA_TAG=v0.30.0` but we're already at v0.30.2 -- I tried just changing the tag and doing a `docker compose build` but it fails.  I'm guessing that newer images need to be built and uploaded to Docker Hub.  I'd be happy to help with that.  In the alternative, could we get a fresher version?

**Comment by 0x4r45h** [comment]
the build should work fine if you have enough resources on your machine, unless a breaking change has been introduced.   
I'll update this to the latest version as soon as I get back home (~ 1 day )

**Comment by 0x4r45h** [comment]
docker image v0.30.2 is now available

**Comment by ekkis** [comment]
a million thanks, and if I can help please let m know
